# Owner of the GitHub repository
owner: SRESchool

# Name of the GitHub repository
repo: All-MyHospitalNow-Websites-Uptime-Monitor

user-agent: pritesh-1904
skipReadme: true
skipDescription: true
skipTopics: true

# List of websites to monitor for uptime and SSL
sites:
  - name: Askdoctorlive
    url: https://ASKDOCTORLIVE.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Bestcardiachospitals
    url: https://BESTCARDIACHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Bestcosmetichospitals
    url: https://BESTCOSMETICHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Bestdentalhospitals
    url: https://BESTDENTALHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Besteyehospitals
    url: https://BESTEYEHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Bestheartsurgery
    url: https://bestheartsurgery.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Bestspinehospitals
    url: https://BESTSPINEHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Cancershospitals
    url: https://CANCERSHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Heartcareforyou
    url: https://HEARTCAREFORYOU.IN
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Hiphospitals
    url: https://HIPHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Kneehospitals
    url: https://KNEEHOSPITALS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Myhospitalnow
    url: https://myhospitalnow.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Mymedicplus
    url: https://MYMEDICPLUS.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: Surgeryplanet
    url: https://SURGERYPLANET.COM
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
    
status-website:
  cname: null
  baseUrl: /All-MyHospitalNow-Websites-Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: All MyHospitalNow Websites Uptime Monitor
  introTitle: MyHospitalNow Websites Status
  introMessage: This page shows the uptime and SSL status of MyHospitalNow Websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.ico
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Workflow schedule (every 5 minutes)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
  ssl: "*/5 * * * *"

# Committer configuration
committer:
  name: Pritesh
  email: contact@motoshare.in

# Email notification configuration
notifications:
  - type: email
    smtpTo: contact@motoshare.in
    smtpFrom: pritesh.thamke@gmail.com
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: "kmxg nshc vsrf kxqj"
    events:
      - up
      - down

# Assignees for issues
assignees:
  - pritesh-1904
